### ISSUE TITLE
Formatting in section titles cause a crash

### ISSUE THREAD

**Issue by antrix** [asciidoctor/asciidoctor-epub3#8] opened 2014-08-12 22:11 UTC
If the source document contains formatting in chapter or section titles, then asciidoctor-epub3 crashes:

```
$ cat bug.adoc
= Asciidoctor EPUB3: Sample Book
Author Name
v1.0, 2014-04-15

== Hello *World*

How do you do
$                   
$ asciidoctor-epub3 --trace bug.adoc                   
/var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/converter.rb:30:in `convert': undefined method `references' for #<Asciidoctor::Inline:0x8487940> (NoMethodError)
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/inline.rb:37:in `convert'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:1178:in `convert_quoted_text'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:381:in `block (2 levels) in sub_quotes'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:381:in `gsub!'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:381:in `block in sub_quotes'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:380:in `each'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:380:in `sub_quotes'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:112:in `block in apply_subs'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:107:in `each'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:107:in `apply_subs'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/substitutors.rb:149:in `apply_title_subs'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/abstract_block.rb:127:in `title'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/section.rb:92:in `generate_id'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/parser.rb:1599:in `initialize_section'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/parser.rb:248:in `next_section'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/parser.rb:291:in `next_section'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/parser.rb:52:in `parse'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:448:in `parse'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1337:in `load'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor.rb:1415:in `convert'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:93:in `block in invoke!'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:85:in `each'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/cli/invoker.rb:85:in `invoke!'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/bin/asciidoctor-epub3:13:in `<top (required)>'
    from /usr/local/bin/asciidoctor-epub3:23:in `load'
    from /usr/local/bin/asciidoctor-epub3:23:in `<main>'
```

**Comment by mojavelinux** [comment] 2017-04-15 09:35
The root cause of this problem was fixed by eb8179e7. We were not accounting for the case of inline conversions in the spine document.

However, your example still won't work because of #47. Since the original issue is resolved, and that issue tracks the new issue, I'm going to close this one.

**Closed by mojavelinux** 2017-04-15 09:35 UTC
Labels: bug
