### ISSUE TITLE
Fails during generation with "undefined method `to_ios'"

### ISSUE THREAD

**Issue by antrix** [asciidoctor/asciidoctor-epub3#7] opened 2014-08-12 22:06 UTC
I've got asciidoctor-epub3 crashing during epub generation on a document that I'm working on. I've been able to reproduce the same crash using the following minimal test case. 

```
$ cat bug.adoc
= Asciidoctor EPUB3: Sample Book
Author Name
v1.0, 2014-04-15

== Hello World

How do you do
$
$ asciidoctor-epub3 bug.adoc
undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x9d68f68>
Use --trace for backtrace
```

Full trace

```
$ asciidoctor-epub3 --trace bug.adoc
/var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:288:in `postprocess_xhtml': undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x8770044> (NoMethodError)
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:235:in `block (3 levels) in add_content'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:233:in `each'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:233:in `each_with_index'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:233:in `block (2 levels) in add_content'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `block in ordered'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in `ordered'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:230:in `block in add_content'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:225:in `add_content'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:407:in `block in package'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
    from /var/lib/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:325:in `new'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/packager.rb:325:in `package'
    from /var/lib/gems/1.9.1/gems/asciidoctor-epub3-1.0.0.dev/lib/asciidoctor-epub3/converter.rb:36:in `write'
    from /var/lib/gems/1.9.1/gems/asciidoctor-1.5.0/lib/asciidoctor/document.rb:1033:in `write'
```

It isn't really clear to me what is triggering this bug. Strangely enough, in my actual document, the bug is triggered in only one scenario. I've got a `master.adoc` within which I include `a.adoc`, `b.adoc`, etc. Running asciidoctor-epub3 on `master.adoc` works fine. But if I don't `include` the files and instead concatenate `master.adoc`, `a.adoc`, `b.adoc` and feed the resulting file to asciidoctor-epub3, then this crash happens.

**Comment by Skilly** [comment] 2016-04-30 09:29
I'm guessing that in the initialize function in packager.rb @spine is getting assigned to a type other than string (possibly an empty array?), if no "spine" is provided

```
  def initialize spine_doc, spine, format = :epub3, options = {}
    @document = spine_doc
    @spine = spine || []
    @format = format
  end
```

**Comment by mojavelinux** [comment] 2016-04-30 22:15
Yes, but the problem goes much deeper than that because the logic in the packager simply doesn't know how to proceed when there is no spine atm. What needs to happen is a spine needs to be created automatically in this case.

**Comment by mojavelinux** [comment] 2017-04-09 08:41
This is a duplicate of #47. Until then, you have to structure your document as documented in the README. See https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript.

**Comment by Patola** [comment] 2017-09-29 05:54
This bug is 3 years old now. Any chance of getting it resolved?

**Comment by mojavelinux** [comment] 2017-09-29 06:09
This is not a bug, it's just how this converter is designed. You have to adhere to the structure described in the README.

(Yes, I'm still considering improving that design to make it more flexible. I just don't have time right now.)

**Comment by mojavelinux** [comment] 2017-09-29 06:10
Since this is covered by #47, I'm closing this one so we can centralize the conversation about the improvement.

**Comment by slonopotamus** [comment] 2020-01-21 21:26
Reopening. While #47 is valid and asciidoctor-epub3 could provide much more flexibility over document organization, we have a smaller problem here: asciidoctor-epub3 fails with cryptic exceptions when given a document that doesn't follow expected structure. We definitely can improve this.

**Closed** 2020-01-21 22:02 UTC
Labels: bug
