### ISSUE TITLE
Handler for Video macro

### ISSUE THREAD

**Issue by willwade** [asciidoctor/asciidoctor-epub3#79] opened 2016-12-08 21:23 UTC
As per @mojavelinux suggestion (http://discuss.asciidoctor.org/Video-in-epub-conversion-tp5137p5140.html) I'm adding an issue for needing a handler for the video macro.

Two suggestions:

* Insert a still image of the video (if it's available) and make it a link to the video. (as in pdf conversion)
* Support video embeds (http://epubzone.org/news/multimedia-support-in-epub-3) 

Thanks!

**Comment by mojavelinux** [comment] 2016-12-15 23:59
The right solution is probably to do both. The video element allows for a fallback. That's where we can put the poster image. The tricker part is YouTube or Vimeo. I'm not sure if those embeds support a fallback. However, I do know that both services provide a thumbnail that can be used as an automatic fallback.

The HTML used in the Bespoke converter is probably pretty close to the HTML we want, but we'll obviously need to do some testing. See https://github.com/asciidoctor/asciidoctor-bespoke/blob/master/templates/slim/video.html.slim

**Comment by mojavelinux** [comment] 2017-04-09 08:47
This is actually a duplicate of #9. I'll just link the two issues.

**Comment by mojavelinux** [comment] 2017-04-09 08:47
I will be testing on the Gitden reader.

**Comment by slonopotamus** [comment] 2020-01-23 16:40
Closing as duplicate of #9.

**Closed by slonopotamus** 2020-01-23 16:40 UTC
Labels: compliance, duplicate
