### ISSUE TITLE
Error >> no epub file produced

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/asciidoctor-epub3#24] opened 2015-02-23 02:45 UTC
With the hml backend, asciidoctor gives a warning, proceeds, and produces an html file.  For epub3: same badness in the source is fatal:no epub produced:

```
$ asciidoctor-epub3 manuscript.adoc 
asciidoctor: WARNING: manuscript.adoc: line 2155: invalid style for paragraph: Catching wild elephants in Burma - photo
undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x007fd8333ca880>
  Use --trace for backtrace
$ re
total 792
-rw-r--r--   1 carlson  staff  394231 Feb 22 21:41 manuscript.adoc
drwxr-xr-x  37 carlson  staff    1258 Feb 22 21:41 images
drwxr-xr-x  92 carlson  staff    3128 Feb 22 21:41 text
-rw-r--r--   1 carlson  staff    3830 Feb 22 21:41 image_manifest.ad
-rw-r--r--   1 carlson  staff    4081 Feb 22 21:41 manifest.ad
$ 
$ asciidoctor-epub3 manuscript.adoc --trace
asciidoctor: WARNING: manuscript.adoc: line 2155: invalid style for paragraph: Catching wild elephants in Burma - photo
/Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:303:in `postprocess_xhtml': undefined method `to_ios' for #<Asciidoctor::Epub3::Packager:0x007fc2f458aa48> (NoMethodError)
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:250:in `block (3 levels) in add_content'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:248:in `each'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:248:in `each_with_index'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:248:in `block (2 levels) in add_content'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `block in ordered'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in `ordered'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:245:in `block in add_content'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `initialize'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `resources'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:240:in `add_content'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:422:in `block in package'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `initialize'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:340:in `new'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/packager.rb:340:in `package'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/lib/asciidoctor-epub3/converter.rb:37:in `write'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1051:in `write'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1504:in `convert'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in `block in invoke!'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `invoke!'
    from /Users/carlson/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/asciidoctor-epub3-1.5.0.alpha.4/bin/asciidoctor-epub3:13:in `<top (required)>'
    from /Users/carlson/.rbenv/versions/2.1.2/bin/asciidoctor-epub3:23:in `load'
    from /Users/carlson/.rbenv/versions/2.1.2/bin/asciidoctor-epub3:23:in `<main>'
```

**Comment by mojavelinux** [comment] 2015-03-31 16:14
Can you point me to the project (or a project that exhibits a similar error). It looks like I'm going to need to do some debugging because this is coming up frequently.

**Comment by mojavelinux** [comment] 2017-04-09 08:39
This is an indication the document is not structured correctly. See https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript.

I'm going to close this as a duplicate of #47 as it's basically the same issue.

**Closed by mojavelinux** 2017-04-09 08:39 UTC
