### ISSUE TITLE
stylus based stylesheets

### ISSUE THREAD

**Issue by gambhiro** [asciidoctor/asciidoctor-epub3#126] opened 2017-08-10 14:22 UTC
Taking the discussion in #114 and starting work on stylus based stylesheets.

**Comment by gambhiro** [comment] 2017-08-10 14:31
The work in PR #127 for now:

Converted the CSS [with a converter][1]. This stripped the comments, so I went through the CSS and put the comments back at the relevant places.

I didn't change the original CSS rules, so all being well, this should generate equivalent CSS to the original, and could be used as is.

I'm planning to go though it later and collect the color values to a palette file using variables.

[1]: http://beautifytools.com/css-to-stylus-converter.php

**Comment by mojavelinux** [comment] 2017-08-12 05:06
I agree with this plan. Let's first reproduce what we have, then we can go to town on the refactoring, knowing that we're starting from a known good state.

**Comment by mojavelinux** [comment] 2017-08-12 05:08
As I mentioned in #114, we need to decide on the development workflow now that we're introducing a preprocessor.

How should the processor be invoked? How will it be integrated into the build? What tools will be required?

To me, the stylus plugin is useless because it's just a wrapper (it invokes an external tool). I'd much rather just execute the tool directly, either from the cli or in a Rake task. That gives us more control.

I does mean that to work with the stylesheets, you'll have to have stylus (and hence node). But I think that's okay. We just need to document the steps and decide when stylus will be invoked in the workflow.

**Comment by mojavelinux** [comment] 2017-08-12 05:14
The open question is this: When should the Stylus files be compiled?

I don't think we should commit the generated CSS files to the repository. That is going to lead to confusion as people will try to submit pull requests against them.

But then when should they be compiled? Obviously, we could compile them when generating the gem. But that makes testing a little harder. Perhaps we can generate them into a build directory and change the packager to look in that location before looking in the data folder. Or it only looks in the data folder when running as an installed gem.

**Comment by gambhiro** [comment] 2017-08-12 11:04
In the current case, I see advantages in the CSS being shipped as a static asset to the user, instead of recompiling on every ebook build.

I say, let's keep the CSS committed in the gem. Someone developing a stylesheet can install stylus and run a watcher when they need it.

The largest drawback would be that the user has to read the documentation and install stylus, which is out of the gem ecosystem.

I understand that asset management is necessary in webdev, when the server has to collect styles from an app stylesheet, add local page styles, combine and compress it and server a versioned CSS file to the client.

This doesn't happen either when developing (in iterations) or when compiling (one instance) of the ebook.

Reviewing the workflow:

This may be trivial but let's go through what happens. When developing the style for an ebook, I do this:

1. open the stylesheet files in the text editor (the stylus files in this case)
2. start a watcher process to re-compile the CSS on save `stylus -w IN_DIR -o OUT_DIR`
3. make changes, save
4. run `asciidoctor-epub3` to generate a new ebook file
5. open the ebook in Calibre's `ebook-viewer`
6. go to the relevant page
7. check the result visually, perhaps open the Inspector to check applied rules on the element

Then repeat 3-7. The ebook has to be compiled into its target format, which then has to be reloaded in the ebook viewer. There is no hot-reloading of any kind or pushing the CSS to the reader. It's like webdev in the old days.

If it was the tool's responsibility to compile from stylus on every build, for development it only means that the stylus watcher doesn't have to be started, and once started, one forgets about it anyway.

For the the user who doesn't want to change the style, it doesn't improve a single ebook compilation if the CSS is generated from stylus, and I think installing stylus (with the whole node shebang) just for this would be irritating for many people.

**Comment by mojavelinux** [comment] 2017-08-13 01:03
I think we're on the same page. We definitely want to ship the default style as CSS so that the end user does not need any additional tools to use it. But that doesn't mean we have to check the CSS into the git repository. The CSS can be prepared when the gem is built and released.

With that said, there are two other workflows. There's the development workflow for the default style and there's the development workflow for a custom theme.

For the custom theme, that's entirely up to the user how to set it up. Users can create their own build to compile to CSS using any tool they want (Sass, LESS, Stylus, etc). The only requirement is that the styles are converted to CSS before they run asciidoctor-epub3.

For developing the default style, we can do something similar. We can have a build that continuously compiles the Stylus to a build directory. When run in development mode, asciidoctor-epub3 will know to look in this directory instead of the data directory.

> The ebook has to be compiled into its target format, which then has to be reloaded in the ebook viewer. There is no hot-reloading of any kind or pushing the CSS to the reader. It's like webdev in the old days.

Sadly, this is the state of eBook development tools today. I've commented on this in other threads that this ecosystem is suffering from a lack of developers. If more developers were involved, bringing their development best practices with them, then these tools would exist.

> If it was the tool's responsibility to compile from stylus on every build, for development it only means that the stylus watcher doesn't have to be started, and once started, one forgets about it anyway.

I'm adamant about the fact that asciidoctor-epub3 should not know about Stylus. That is a development detail. But we can create a build that will provide this type of interface. It's something Rake can handle.

**Comment by mojavelinux** [comment] 2017-08-13 01:08
In short, we could have an interface like:

```
asciidoctor-epub3-dev
```

That will compile the Stylus to CSS and run asciidoctor-epub3. We can just add another command to bin which is not shipped with the gem. As we play around with it I'm sure we'll find the approach which is most comfortable.

**Comment by mojavelinux** [comment] 2017-08-13 01:09
There's really no point in running a watcher since you have to call asciidoctor-epub3 anyway to build the ebook. So we'll just run Stylus when the book is made in dev mode.

**Comment by slonopotamus** [comment] 2020-03-04 18:58
I've read through this and #114 about a hundred of times, but goal is still unclear.

Do we perform stylesheet conversion *during book conversion* so users are able to utilize more advanced tools than pure CSS? If yes, we need something that easily installs when someone does `gem install asciidoctor-epub3`. This throws away every CSS processor except [SASS](https://rubygems.org/gems/sassc). And even it has issues installing on JRuby+Windows.

Or do we want a tool for developing asciidoctor-epub3 *itself*? Then workflow isn't clear. Storing both Stylus/SASS *plus* CSS in repo is error-prone and inconvenient to use.

**Comment by gambhiro** [comment] 2020-03-04 20:42
It's been a while now, and by all means close this if no longer seems relevant.

The motivation on my part was to use stylesheets which can be easily copied from the main project, customized for specific books (say, change the text color grey value or add custom heading styles), generate and embed the new CSS.

I still do that, I copy the whole asciidoctor-epub3 to a vendor folder for each book and change the stylesheets there.

Perhaps a command line option to save the CSS or SASS from the installed gem to the local project would be a more streamlined method, and then the user can specify with an option where the local stylesheet folder is. Sometimes they call this 'ejecting' the templates or stylesheets.

**Comment by slonopotamus** [comment] 2020-03-04 20:50
> The motivation on my part was to use stylesheets which can be easily copied from the main project, customized for specific books (say, change the text color grey value or add custom heading styles), generate and embed the new CSS.

Makes sense. User even now can use whatever tools they want to produce CSS that is feeded into asciidoctor-epub3.

> close this if no longer seems relevant

I'm not sure yet. If there were no issues with SASS on JRuby, I'd just say "yay, let's go SASS!" and be done with it. I rwally believe that ease of installation is very important. We must also keep in mind that part of users use us through Maven/Gradle. They even have troubles installing Kindlegen/EPUBCheck!

Dunno, need to think more about this.

**Comment by slonopotamus** [comment] 2020-03-05 06:52
Tried adding dependency on `sassc` gem across our supported platforms: https://github.com/slonopotamus/asciidoctor-epub3/actions/runs/49927345

Yep, JRuby+Windows just cannot install it.

**Comment by slonopotamus** [comment] 2020-12-06 15:30
Let's sum it up.

CSS conversion on end-user machine doesn't work because the world have *any* CSS preprocessor that could easily be installed as asciidoctor-epub3 dependency. Ruby Sass would work, but it's development was shut down. LibSass-based sassc-ruby requires setting up C compiler toolchain, which is too much of a burden for JRuby and Windows environments.

We also don't want to commit both Sass and CSS files to repo.

So, the only working way is to perform conversion during gem packaging (and during development, of course). This will allow users to generate their own variants of CSS for ebooks, but will complicate our build procedure a bit.

**Closed** 2022-12-19 18:10 UTC
Labels: enhancement
