### ISSUE TITLE
Custom link texts not supported in cross-references, and only titles can be linked

### ISSUE THREAD

**Issue by programandala-net** [asciidoctor/asciidoctor-epub3#317] opened 2020-03-03 00:43 UTC
Since finally documents are no longer required to use a spine file, I can use asciidoctor-epub3 for the first time to convert my Asciidoctor documents to EPUB directly instead of other alternatives via DocBook, like Pandoc and dbtoepub.

But despite standard `<<anchor>>` and `<<file.adoc#anchor>>` are now supported, it seems `<<anchor, link text>>` is not yet, right?

I have written a test document, and it seems `<<anchor>>` links work when "anchor" is a title id, or an explicit id associated to a title, but the link text is always ignored and the target title is used instead.

Also, when `<<anchor,link text>>` leads to arbitrary points in the document (no matter defined by `[[anchor]]`, `[id=anchor]` or `[#anchor]`), it displays "link text", but the link doesn't work.

Last, in the combination `<<anchor>>` and `[[anchor,link text]]` the link text is used in the cross reference as expected, but the link still doesn't work.

In the HTML conversion of the same test document all cross references look and work fine.

**Comment by slonopotamus** [comment] 2020-03-03 06:53
> it seems `<<anchor, link text>>` is not yet, right?

It was supposed to be supported, but failed due to a bug. I've already got a fix for that: #318

> Also, when <<anchor,link text>> leads to arbitrary points in the document (no matter defined by [[anchor]], [id=anchor] or [#anchor]), it displays "link text", but the link doesn't work.

Please, provide an example document. I have a [test case for inline anchor](https://raw.githubusercontent.com/asciidoctor/asciidoctor-epub3/master/spec/fixtures/inline-anchor-xref/chapter.adoc) and it works properly.

> Last, in the combination <<anchor>> and [[anchor,link text]] the link text is used in the cross reference as expected, but the link still doesn't work.

Look like this is the same problem as the second one.

**Comment by programandala-net** [comment] 2020-03-03 13:16
> > I can use asciidoctor-epub3 for the first time to convert my Asciidoctor documents to EPUB directly
> 
> That's cool, actually. I had a strong feeling that spine requirements on document structure blocked some people from using asciidoctor-epub3.

Indeed. Many of my documents are software manuals which are built automatically from the source code. The spine structure was a serious inconvenient. Other documents of mine, book translations and such, are easier to edit as a single file, not divided into many chapter files. The spine requirement was very restrictive.

> Please, provide an example document. I have a [test case for inline anchor (https://raw.githubusercontent.com/asciidoctor/asciidoctor-epub3/master/spec/fixtures/inline anchor-xref/chapter.adoc) and it works properly.

I upload my test file, with all possible types of cross references and the description of their result in EPUB. Conversion to HTML works fine.

[cross_1_test.adoc.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4281428/cross_1_test.adoc.zip)

**Comment by slonopotamus** [comment] 2020-03-03 13:19
> I upload my test file, with all possible types of cross references and the description of their result in EPUB.

Thanks.

**Comment by programandala-net** [comment] 2020-03-03 13:28
By mistake I deleted this line at the end of the first chapter:

`The subject of the <<mychapter1,first chapter of mine>> is
interesting (the link text should be "first chapter of mine").`

[cross_1_test.adoc.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/4281489/cross_1_test.adoc.zip)

**Comment by slonopotamus** [comment] 2020-03-03 16:25
```
The subject of the <<mychapter1,first chapter of mine>> is
interesting (the link text should be "first chapter of mine").
```

Fixed by #318

```
Beside, you can see <<many,many things>> (the link text should read
"many things"; the link doesn't work):
```

Link text fixed by #318, link not working fixed by #319

```
But there are <<few,few things>> here (the link text should read "few
things"; the link doesn't work):
```

Link text fixed by #318, link not working fixed by #319 

```
Also visit <<other,other things>> (the link text should read "other
things"; the link doesn't work):
```

Link text fixed by #318, link not working fixed by #319

```
[id=mychapter2,second chapter of mine]
== My second chapter
```

I fail to see where this is allowed by [Asciidoctor docs](https://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text). And it in fact doesn't work because "second chapter of mine" text isn't available to converter, neither for EPUB3 nor for HTML. Maybe you wanted to say this:

```
[id=mychapter2,reftext="second chapter of mine"]
== My second chapter
```

**Closed by slonopotamus** 2020-03-03 16:25 UTC
Labels: bug, compliance

**Comment by programandala-net** [comment] 2020-03-03 18:13
> ```
> [id=mychapter2,second chapter of mine]
> == My second chapter
> ```
> 
> I fail to see where this is allowed by [Asciidoctor docs](https://asciidoctor.org/docs/user-manual/#customizing-the-cross-reference-text). And it in fact doesn't work because "second chapter of mine" text isn't available to converter, neither for EPUB3 nor for HTML. Maybe you wanted to say this:
> 
> ```
> [[mychapter2,second chapter of mine]]
> == My second chapter
> ```

You are right, sorry. I confused the syntaxes in the last version of the test file.

Thank you for the fixes.

**Comment by slonopotamus** [comment] 2020-03-03 18:23
> Thank you for the fixes.

Well, there will a little bit of delay before alpha-15 because I want to fix some more things and wait for feedback. Removal of spine limitations touched *a lot* of code and given our pretty low test coverage, other regressions besides #318 could be introduced.

Interestingly, #319 is not a regression. Possibly anchoring plain paragraphs isn't very common.

So, If you encounter more problems, feel free to report them.
