### ISSUE TITLE
Can't generate epub: undefined method `to_ios' 

### ISSUE THREAD

**Issue by yfain** [asciidoctor/asciidoctor-epub3#25] opened 2015-03-30 21:09 UTC
I have a pretty simple adoc file and asciidoctor 1.5.2. Tried to generate epub and got this:

$ asciidoctor-epub3 joiningCTOschool.adoc
undefined method `to_ios' for #Asciidoctor::Epub3::Packager:0x007faf990a79e0
  Use --trace for backtrace

Running with --trace produced this:

Yakov:ctoschool yfain11$ asciidoctor-epub3 --trace joiningCTOschool.adoc
/Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:303:in `postprocess_xhtml': undefined method`to_ios' for #Asciidoctor::Epub3::Packager:0x007f99db82d288 (NoMethodError)
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:250:in `block (3 levels) in add_content'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:248:in`each'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:248:in `each_with_index'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:248:in`block (2 levels) in add_content'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in `instance_eval'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:40:in`block in ordered'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/package.rb:166:in `ordered'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/book.rb:205:in`ordered'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:39:in `ordered'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:245:in`block in add_content'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in `instance_eval'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/resource_builder.rb:33:in`initialize'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in `new'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:292:in`resources'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:240:in `add_content'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:422:in`block in package'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in `instance_eval'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/gepub-0.6.9.2/lib/gepub/builder.rb:185:in`initialize'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:340:in `new'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/packager.rb:340:in`package'
    from /Users/yfain11/asciidoctor-epub3/lib/asciidoctor-epub3/converter.rb:37:in `write'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/asciidoctor-1.5.2/lib/asciidoctor/document.rb:1051:in`write'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1504:in `convert'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:94:in`block in invoke!'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in `each'
    from /Users/yfain11/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/asciidoctor-1.5.2/lib/asciidoctor/cli/invoker.rb:86:in`invoke!'
    from /Users/yfain11/asciidoctor-epub3/bin/asciidoctor-epub3:13:in `<main>'

**Comment by mojavelinux** [comment] 2015-03-30 21:14
If I remember correctly, Asciidoctor EPUB3 is fussy about having just the right structure for the document. We obviously want to fix this. Until then, refer to the following example and be sure to follow the same structure, working backwards from the example to your doc.

https://github.com/asciidoctor/asciidoctor-epub3/blob/master/data/samples/sample-book.adoc

**Comment by mojavelinux** [comment] 2015-03-30 21:15
To provide some context...Asciidoctor EPUB3 was flexible to handle any AsciiDoc document at one point, but somewhere along the line I broke it. Tests would obviously be a huge benefit here :)

**Comment by mojavelinux** [comment] 2017-04-09 08:37
I have detailed the required structure in the README. See https://github.com/asciidoctor/asciidoctor-epub3#structuring-your-manuscript

**Comment by mojavelinux** [comment] 2017-04-09 08:38
I'm going to close this as a duplicate of #47. It's the same issue.

**Closed by mojavelinux** 2017-04-09 08:38 UTC
Labels: bug, next
