### ISSUE TITLE
large numbers of `invalid reference to unknown anchor` (2)

### ISSUE THREAD

**Issue by pponec** [asciidoctor/asciidoctor-epub3#381] opened 2020-11-12 20:55 UTC
Hello, 
I have a similar problem that was described in issue: https://github.com/asciidoctor/asciidoctor-epub3/issues/210

```text
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: hello
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: visibility
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: visibility
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: stream
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: drawing
```
in the release: 

```text
$ asciidoctor-epub3 -v
Asciidoctor EPUB3 1.5.0.alpha.18 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

**Comment by slonopotamus** [comment] 2020-11-25 11:08
Could you provide a minimal document that reproduces your issue?

**Comment by slonopotamus** [comment] 2020-12-06 13:54
Closing due to lack of info.

**Comment by pponec** [comment] 2021-01-09 11:20
> Could you provide a minimal document that reproduces your issue?

I apologize for the delay, the required files are attached.

The output contains the next message:

```text
asciidoctor: WARNING: book.asciidoc: invalid reference to unknown anchor: classMethod
```

[epub-project.zip](https://github.com/asciidoctor/asciidoctor-epub3/files/5790566/epub-project.zip)

**Comment by slonopotamus** [comment] 2021-01-09 14:42
Okay, this is the same problem as #331. Please, see workaround: https://github.com/asciidoctor/asciidoctor/issues/3633#issuecomment-620402331

**Comment by pponec** [comment] 2021-01-09 20:46
> Okay, this is the same problem as #331

I confirm that the workaround solved my problem, thank you.

**Closed** 2021-01-09 20:59 UTC
Labels: bug
