### ISSUE TITLE
XML ids cannot start with a number

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/asciidoctor-epub3#75] opened 2016-06-07 01:23 UTC
This weekend I received a new error for an existing chapter when I uploaded an update to Leanpub. Apparently they upgraded their internal checks for epub documents and are now using epubcheck.

The error I received was:

```
value of attribute "id" is invalid; must be an XML name without colons
```

I found the solution here: https://github.com/IDPF/epubcheck/issues/307

My asciidoc file has a section title that starts with a number, like the following:

```
== 3 Blind Mice
```

When this was converted to epub format it came out as:

```
<section class="sect1" title="3 Blind Mice">
<h2 id="3-blind-mice">3 Blind Mice</h2>
```

I rephrased the title and it passed the checks.  

My suggestion is for asciidoctor-epub3 to detect when a section title starts with a number and prefix its generated id with a letter.

**Comment by mojavelinux** [comment] 2016-06-07 04:25
Thanks for tracking this down. This change actually needs to go into core, where IDs are generated.

As a workaround, you can assign an explicit ID in cases like this:

```
[#three-blind-mice]
== 3 Blink Mice
```

You are absolutely correct, though, that an ID cannot start with a number. See https://www.w3.org/TR/REC-xml/#NT-Name

**Comment by mojavelinux** [comment] 2017-04-08 10:51
Another solution is to set the `idprefix` attribute to `_`. This is one of the dangers of setting the `idprefix` attribute to blank (there are others).

**Comment by mojavelinux** [comment] 2017-04-11 05:57
These IDs are set in core, not in Asciidoctor EPUB3. Thus, I've opened an issue in core. See https://github.com/asciidoctor/asciidoctor/issues/2117.

Once the issue is resolve in core, you can fix Asciidoctor EPUB3 simply by upgrading Asciidoctor. Therefore, I'm closing the issue here.

**Closed by mojavelinux** 2017-04-11 05:57 UTC
