### ISSUE TITLE
xrefs to sections in other chapters don't seem to work properly

### ISSUE THREAD

**Issue by michaelpj** [asciidoctor/asciidoctor-epub3#202] opened 2019-07-08 11:18 UTC
Following the text in Rule 4:

> If you want to reference a section in a chapter, update the fragment (i.e., the value that follows the hash) to match the target section ID.

doesn't seem to actually work. The link in the epub output actually does work, but it has the no reftext, and during generation you get warnings like:
```
asciidoctor: WARNING: ch1.adoc: invalid reference to unknown anchor in ch2: test
```

**Comment by slonopotamus** [comment] 2020-01-20 22:20
I believe this is a duplicate of #210. Please, test with asciidoctor-epub3 1.5.0.alpha.10.

**Closed by slonopotamus** 2020-01-20 22:20 UTC
