### ISSUE TITLE
asciidoctor: ERROR: KindleGen failed to write MOBI

### ISSUE THREAD

**Issue by amejiarosario** [asciidoctor/asciidoctor-epub3#362] opened 2020-08-23 17:29 UTC
I'm getting this error after I updated this gem to master. (epub works fine btw)

```
asciidoctor: ERROR: KindleGen failed to write MOBI to /mnt/c/Users/adria/Code/dsa.js/book/dist/dsajs-book-vsnapshot.mobi
```

I even tried downloading the kindlegen manually and passing it in KINDLEGEN but still no go
```
 env VERSION='0' KINDLEGEN=(pwd)"/bin/kindlegen" bundle exec asciidoctor --backend=epub3 --require=asciidoctor-epub3 -a ebook-validate  -a ebook-format=kf8 --trace --require=asciidoctor-diagram --destination-dir=../dist -a revnumber=snapshot ../readme.asc --out-file=../dist/dsajs-book-snapshot.mobi
```

**Comment by slonopotamus** [comment] 2020-08-23 19:42
@amejiarosario I need some more log output. Our "KindleGen failed to write MOBI" error just means that execution of KindleGen ended with non-zero exit code.

**Comment by amejiarosario** [comment] 2020-08-24 00:00
@slonopotamus I added the `--verbose` flag and got some more data.  I'm using Ubuntu WSL (Windows Subsystem for Linux).

```
bin/kindlegen: Syntax error: "(" unexpected
```
full logs:
```
$ bundle exec asciidoctor --verbose --backend=epub3 --require=asciidoctor-epub3 -a ebook-validate -a ebook-format=kf8 --trace --requuire=asciidoctor-diagram --destination-dir=../dist -a revnumber=0 ../readme.asc --out-file=../dist/dsajs-book-v0.mobi

/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gepub-1.0.11/lib/gepub/package.rb:174: warning: instance variable @ordered not initialized
/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gepub-1.0.11/lib/gepub/book.rb:131: warning: instance variable @optional_files not initialized
/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/gems/gepub-1.0.11/lib/gepub/metadata.rb:99: warning: instance variable @xml not initialized
asciidoctor: DEBUG: Wrote KF8 to /mnt/c/Users/adria/Code/dsa.js/book/dist/dsajs-book-v0-kf8.epub
asciidoctor: DEBUG: Using KindleGen from gem: /home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen
asciidoctor: INFO: /home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen: 1: /home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen: Syntax error: "(" unexpected
asciidoctor: ERROR: KindleGen failed to write MOBI to /mnt/c/Users/adria/Code/dsa.js/book/dist/dsajs-book-v0.mobi
```

Let me know if you need anything else

**Comment by slonopotamus** [comment] 2020-08-24 09:43
Seems like something went wrong when installing `kindlegen` gem. `/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen` is supposed to be an executable file. What does it contain?

**Comment by amejiarosario** [comment] 2020-08-24 10:48
It's an executable binary file (ELF4). I tried to run it on its own and looks like is failing:

- `bin/kindlegen' is marked as an executable but could not be run by the operating system.`
- `bin/kindlegen: cannot execute binary file: Exec format error`

I also get the same error when trying to run the file I downloaded it ` kindlegen_linux_2.6_i386_v2_9.tar.gz`. Not sure why won't work in Ubuntu.


Full logs:
```
$ /home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen 

Failed to execute process '/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen'. Reason:
exec: Exec format error
The file '/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen' is marked as an executable but could not be run by the operating system.
```

```
$ bash -c '/home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen'                        06:42:51
bash: /home/adrian/.asdf/installs/ruby/2.6.5/lib/ruby/gems/2.6.0/bundler/gems/kindlegen-12dd349ce59f/bin/kindlegen: cannot execute binary file: Exec format error
```

**Comment by slonopotamus** [comment] 2020-08-24 10:58
Hmm... I've noticed that you're using non-release version of `kindlegen` gem but commit [12dd349ce59f](https://github.com/tdtds/kindlegen/commit/12dd349ce59f) that is almost 6 years old. Could you try updating to latest `kindlegen` release (3.0.5)?

**Comment by slonopotamus** [comment] 2020-08-24 11:29
Also, does your kernel support running 32-bit executables at all? That could also be the cause of the problem.

**Comment by slonopotamus** [comment] 2020-08-25 10:04
Closing this in favor of #363.

**Closed by slonopotamus** 2020-08-25 10:04 UTC
Labels: bug

**Comment by amejiarosario** [comment] 2020-08-25 23:53
I tried again on Ubuntu 20.04 (before 18.04) and with a newer version of ruby 2.7 (before 2.5) and reinstalled everything. It's working now 🤷‍♂️
