### ISSUE TITLE
Strange inter chapter link errors

### ISSUE THREAD

**Issue by jnavila** [asciidoctor/asciidoctor-epub3#139] opened 2017-10-22 19:35 UTC
Trying to make the second edition of Progit ready for asciidoctor, I changed the structure of files to match the description.

When compiling the book, I get the following errors:
```
± bundle exec asciidoctor-epub3 progit.asc
/home/jnavila/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
/home/jnavila/.rvm/gems/ruby-2.4.0/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/document.rb:44: warning: constant ::Fixnum is deprecated
asciidoctor: WARNING: 03-git-branching.adoc: invalid reference to unknown local anchor (or valid bibref): <em>basic_merging
asciidoctor: WARNING: 04-git-server.adoc: invalid reference to unknown local anchor (or valid bibref): <em>gitlab_groups_section
asciidoctor: WARNING: 06-github.adoc: invalid reference to unknown local anchor (or valid bibref): <em>pr_final
asciidoctor: WARNING: 06-github.adoc: invalid reference to unknown local anchor (or valid bibref): <em>org_page
asciidoctor: WARNING: 07-git-tools.adoc: invalid reference to unknown anchor in 03-git-branching chapter: <em>rebase_peril
asciidoctor: WARNING: 07-git-tools.adoc: invalid reference to unknown local anchor (or valid bibref): <em>commit_ranges
asciidoctor: WARNING: 08-customizing-git.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>revision_selection
asciidoctor: WARNING: 10-git-internals.adoc: invalid reference to unknown anchor in 08-customizing-git chapter: <em>enforcing_commit_message_format
asciidoctor: WARNING: B-embedding-git.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>branch_references
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 02-git-basics chapter: <em>undoing
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 02-git-basics chapter: <em>viewing_history
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 05-distributed-git chapter: <em>private_team
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>merge_log
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>signing_commits
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>revision_selection
asciidoctor: WARNING: C-git-commands.adoc: invalid reference to unknown anchor in 07-git-tools chapter: <em>reverse_commit
```

Most of the internal links are correctly resolved, but some of them fail, whereas they work correctly for pdf.

You can access the corresponding data at https://github.com/progit/progit2-fr/tree/reorder_files

**Comment by mojavelinux** [comment] 2017-10-23 03:37
Some of these may actually be valid. Asciidoctor cannot yet correctly identify all references, so it puts out a conservative warning. This is something being addressed in the upcoming release of core. See https://github.com/asciidoctor/asciidoctor/issues/2257.

I'll go ahead and give the book a try to make sure something else is going on...but I'm pretty sure it's the problem I referenced.

**Comment by mojavelinux** [comment] 2017-10-23 06:10
Disregard my comment. That wasn't it at all,

The problem is that the underscore at the start of the fragment is being interpreted as a formatting mark. That's why we're seeing `<em>` in the message.

Take this sentence for example:

```
Dans <<02-git-basics#_undoing>>, nous couvrons l'utilisation de l'option `--amend` pour refaire le _commit_ le plus récent.
```

Since `#` is a word boundary, the single `_` at the start of the fragment gets paired with the underscore at the end of "commit".

To fix this problem, you can escape the underscore in the fragment:

```
Dans <<02-git-basics#\_undoing>>, nous couvrons l'utilisation de l'option `--amend` pour refaire le _commit_ le plus récent.
```

Unfortunately, escaping formatting marks is highly contextual. You can only escape a character that is currently forming a match. Otherwise, the backslash won't get removed.

This is of the main reasons I recommend against using `_` as the ID prefix. It's too easily confused as a formatting mark. It's much better to use no ID prefix or start the ID prefix with a word character, like "s_".

**Comment by mojavelinux** [comment] 2017-10-23 06:15
You could also reference the `idprefix` attribute specifically, though you'd first need to set it at the top of the document or book.

```
:idprefix: _

...

Dans <<02-git-basics#{idprefix}undoing>>, nous couvrons l'utilisation de l'option `--amend` pour refaire le _commit_ le plus récent.
```

**Comment by mojavelinux** [comment] 2017-10-23 06:16
(I still think it's better just to drop the underscore from the beginning of the ID).

**Comment by jnavila** [comment] 2017-10-23 09:18
No problem reformatting the ids in the text. I guess it was primarily done in the first place to avoid conflicts with auto-generated id when the processing was done by O'Reilly's Atlas.

This reformatting can be thought as a part of making the source compliant with asciidoctor's processing. I'll take the road of adding as small 's' before each underscore prefix.

Btw, great piece of software, we use it to generate all the pages of the manual and the progit book on git-scm.com. The present work aims at proposing again the ebooks and pdfs of the books in original and in their translations.

**Closed** 2017-10-28 20:12 UTC
