### ISSUE TITLE
keep getting error when running on ruby 2.6.3

### ISSUE THREAD

**Issue by jackalcooper** [asciidoctor/asciidoctor-epub3#208] opened 2019-08-22 03:05 UTC
trace:
```
jackal$ asciidoctor-epub3 --trace x.adoc
Traceback (most recent call last):
	27: from /Users/jackal/.asdf/installs/ruby/2.6.3/bin/asciidoctor-epub3:23:in `<main>'
	26: from /Users/jackal/.asdf/installs/ruby/2.6.3/bin/asciidoctor-epub3:23:in `load'
	25: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-epub3-1.5.0.alpha.9/bin/asciidoctor-epub3:32:in `<top (required)>'
	24: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `invoke!'
	23: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:111:in `each'
	22: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/cli/invoker.rb:128:in `block in invoke!'
	21: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `convert_file'
	20: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `open'
	19: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:183:in `block in convert_file'
	18: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/convert.rb:124:in `convert'
	17: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb:978:in `write'
	16: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/converter.rb:41:in `write'
	15: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/packager.rb:508:in `package'
	14: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/packager.rb:508:in `new'
	13: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/builder.rb:187:in `initialize'
	12: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/builder.rb:187:in `instance_eval'
	11: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/asciidoctor-epub3-1.5.0.alpha.9/lib/asciidoctor-epub3/packager.rb:563:in `block in package'
	10: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/builder.rb:196:in `block (2 levels) in <class:Builder>'
	 9: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/book.rb:168:in `method_missing'
	 8: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `add_date'
	 7: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/metadata.rb:164:in `add_date'
	 6: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/metadata_add.rb:126:in `add_metadata'
	 5: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/metadata.rb:176:in `add_metadata_internal'
	 4: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/metadata.rb:176:in `new'
	 3: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/gepub-1.0.4/lib/gepub/datemeta.rb:8:in `initialize'
	 2: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/time.rb:375:in `parse'
	 1: from /Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/time.rb:266:in `make_time'
/Users/jackal/.asdf/installs/ruby/2.6.3/lib/ruby/2.6.0/time.rb:266:in `local': argument out of range (ArgumentError)
```

**Comment by slonopotamus** [comment] 2020-01-19 15:19
@jackalcooper Could you please show your asciidoc header? Seems like there's some issue with date parsing.

**Comment by mojavelinux** [comment] 2020-01-20 09:55
Agree, Asciidoctor EPUB3 is more strict and requires the revision date to be a parsable date.

**Comment by slonopotamus** [comment] 2020-01-20 19:08
Duplicate of #14.

**Closed by slonopotamus** 2020-01-20 19:08 UTC
