### ISSUE TITLE
Download Kindlegen if it can't be found

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-epub3#44] opened 2015-10-29 22:02 UTC
If Kindlegen can't be found (because the gem wasn't install or we can't install gems like in AsciidoctorJ), then download Kindlegen on demand, extract it to a temporary location and use that executable. This will allow mobi generation to work consistently everywhere and will give us control over the Kindlegen download.

**Comment by ysb33r** [comment] 2019-03-31 14:41
In the Gradle plugin for Asciidoctor we take care of this automatically, but it fails on Windows due to an issue on how kindlegen access is imlementd in the GEM.

**Comment by slonopotamus** [comment] 2020-01-22 16:54
@ysb33r Could you provide more details please? We could possibly send a PR to kindlegen gem to fix that?

Overall, I don't quite understand this issue. Kindlegen should not be any different from epubcheck, for example.

**Comment by ysb33r** [comment] 2020-01-22 17:49
IIRC the issue is that the only way to run it is to have it on the path, otherwise the GEM does not find it. Setting `KINDLEGEN` environmental variable does not seem to work for Windows even though it should. See https://github.com/asciidoctor/asciidoctor-epub3/blob/c81bd96e1def27dce92b60093da9d2cc9cefe276/lib/asciidoctor-epub3/packager.rb#L478 

The issue is described here asciidoctor/asciidoctorj#659.

Ideally if the kindlegen location is passed via seom option or attribute it could also help.

**Comment by slonopotamus** [comment] 2020-01-22 17:59
Thanks for the link, I'll try to figure out what's going on.

**Comment by ysb33r** [comment] 2020-01-22 17:59
IIRC the issue is that the only way to run it is to have it on the path, otherwise the GEM does not find it. Setting `KINDLEGEN` environmental variable does not seem to work for Windows even though it should. See https://github.com/asciidoctor/asciidoctor-epub3/blob/c81bd96e1def27dce92b60093da9d2cc9cefe276/lib/asciidoctor-epub3/packager.rb#L478 

The issue is described here asciidoctor/asciidoctorj#659. It only occurs under JRuby. A good solution for us is might be to only half generate the files and then post-process them. IOW tell the GEM to only generate the files require by kindlegen, but not call it. In that way we can post-process from maven or gradle by calling kindlegen from the build tool after the GEM has generated the intermediate artifacts.

**Comment by mojavelinux** [comment] 2020-01-22 19:26
That seems like a bad idea. We shouldn't be putting workarounds in place because of a bug. Instead, the focus should be on why it is failing. The invocation of kindlegen should be encapsulated by this converter.

**Comment by ysb33r** [comment] 2020-01-22 20:25
@mojavelinux Irrespective on that concern, having the ability to set the exact path to  kindlegen without relying on setting an environmental variable is very useful. For instance is we run asciidoctorj inside the same JVm we cannot use an envVar. 

Also having access to the intermediate artifacts can be useful in certain cases.

**Comment by mojavelinux** [comment] 2020-01-22 21:10
I don't see why we are even talking about an environment variable. The call to kindlegen should be encapsulated inside the gem. There should be no environment variable involved.

> Also having access to the intermediate artifacts can be useful in certain cases.

I'm not arguing against that and I can definitely see the value.

**Comment by slonopotamus** [comment] 2020-01-22 21:31
> I don't see why we are even talking about an environment variable.

1. Because the world is not ideal and [sometimes](https://github.com/asciidoctor/asciidoctor-epub3/issues/236) people will have to know that we have `kindlegen` inside. In the ideal world, [asciidoctor-gradle-examples](https://github.com/asciidoctor/asciidoctor-gradle-examples) would even have a test project that reproduces this issue.
2. Because there is an environment variable to control path to `kindlegen`

Anyway, if we're failing to run `kindlegen` on Windows while running from within JRuby, it is a bug that we can reproduce, analyze and finally fix. And I'm actually going to do that in some maybe-even-nearest future.

**Comment by mojavelinux** [comment] 2020-01-22 21:35
> Because the world is not ideal and sometimes people will have to know that we have kindlegen inside.

I get that. I'm not advocating against the environment variable. I'm advocating against relying on it to fix a bug of kindlegen not being found.

> Anyway, if we're failing to run kindlegen on Windows while running from within Gradle, it is a bug that we can reproduce, analyze and finally fix.

1000% Exactly what I'm saying. If we have to download it ourselves because the kindlegen gem fails to do so (or properly), then let's just bite that bullet and do it.

**Comment by slonopotamus** [comment] 2020-01-22 22:15
@mojavelinux while we're at it: [asciidoctor/asciidoctor-gradle-examples](https://github.com/asciidoctor/asciidoctor-gradle-examples) seems to be very much abandoned. Would someone be able to review and merge PRs there if I submitted them or it is better to request commit access from you?

**Comment by mojavelinux** [comment] 2020-01-22 22:17
I don't manage that project. I would suggest asking in the asciidoctor/asciidoctorj gitter channel.

**Comment by slonopotamus** [comment] 2020-01-22 22:18
Okay

**Comment by slonopotamus** [comment] 2020-01-23 16:34
I declare that this issue is a duplicate of #154.

**Closed by slonopotamus** 2020-01-23 16:34 UTC
Labels: enhancement
